feat: 관리자의 방제목 수정 기능
mash-up-kr/TDTD_Backend pull request #29
Opened 2021-07-26 04:56 UTC by secureWKkim

## [ #24 ] 관리자의 방제목 수정 기능

## 🔎 작업 내용
- 무엇을 했나요?
관리자의 방 제목 수정 기능 개발

## ❔Question
roomRepository에 새로 만든 updateByRoomCode 메서드 부분에서 에러가 납니다.
메서드의 파라미터로 넘어온 newTitle을 @Query 안에서 인식하지 못하더라고요.
에러 메시지도 이 부분에서 의존성 문제가 있다는 내용으로 에러가 났습니다.
patch 메서드를 처음 만들어보는데, 더 필요한 어노테이션 같은게 있는 걸까요?
아님 null 일 경우의 처리를 제대로 안한게 문제인걸까요?
여러 생각이 드는데 조언 부탁드립니다. 😢

## 🚫 Full Error Message
> `UnsatisfiedDependencyException: Error creating bean with name 'commentController' defined in file [/Users/wonkyungkim/Documents/GitHub/TDTD_Backend/build/classes/kotlin/main/mashup/backend/tdtd/comment/controller/CommentController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'commentService' defined in file [/Users/wonkyungkim/Documents/GitHub/TDTD_Backend/build/classes/kotlin/main/mashup/backend/tdtd/comment/service/CommentService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'roomRepository' defined in mashup.backend.tdtd.room.repository.RoomRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Using named parameters for method public abstract void mashup.backend.tdtd.room.repository.RoomRepository.updateByRoomCode(java.lang.String,java.lang.String) but parameter 'Optional[newTitle]' not found in annotated query 'update Room r set r.title =: newTitle where r.roomCode=:roomCode'!`

2021-07-26 05:36 UTC, JaeHyeonKim19 requested changes
다음 풀리퀘스트 올릴 때 .DS_Store 파일은 빼고 올려줘~ .DS_Store는 맥에서 해당 폴더에대한 메타데이터 저장하는 용도로 생성하는 파일이라 프로젝트에는 포함안되는게 좋을꺼같아. 관련해서 .gitignore파일은 업데이트 하도록할께~

2021-07-26 05:36 UTC, JaeHyeonKim19 commented on src/main/kotlin/mashup/backend/tdtd/room/repository/RoomRepository.kt
> +    @Query("update Room r set r.title =: newTitle where r.roomCode=:roomCode")
: 랑 newTitle 사이에 띄워쓰기 때문에 빌드가 안되고 있네 아래처럼 수정해주면 정상실행될거야
`=: newTitle` -> `=:newTitle`

2021-07-26 05:36 UTC, JaeHyeonKim19 commented on src/main/kotlin/mashup/backend/tdtd/room/repository/RoomRepository.kt
> +    @Query("update Room r set r.title =: newTitle where r.roomCode=:roomCode")
그리고 JPA 사용하면 update 경우 이렇게 쿼리문 사용하지않고 엔티티의 필드값을 수정해서 데이터베이스에 반영할 수 있거든. 해당방법으로 하는게 더 좋을거 같아. 이렇게 사용하면 ORM을 사용하는 장점이 줄어들거같네

2021-07-26 06:51 UTC, jongnan commented on src/main/kotlin/mashup/backend/tdtd/room/repository/RoomRepository.kt
> +    @Query("update Room r set r.title =: newTitle where r.roomCode=:roomCode")
위 의견에 동의합니다~

2021-07-27 01:28 UTC, secureWKkim commented on src/main/kotlin/mashup/backend/tdtd/room/repository/RoomRepository.kt
> +    @Query("update Room r set r.title =: newTitle where r.roomCode=:roomCode")
오 나도 그렇게 하고싶었는데 뭘 어떻게 써서 해야하는지 몰라갖고 저렇게 했거든... 그런 기능 없는줄로 알고...!

2021-07-27 01:29 UTC, secureWKkim commented on src/main/kotlin/mashup/backend/tdtd/room/repository/RoomRepository.kt
> +    @Query("update Room r set r.title =: newTitle where r.roomCode=:roomCode")
그럼 지금 그렇게 할수있는 방법 리서치 한번 해보고 그래도 몰겠으면 직접 물어보도록 할게!

2021-07-27 03:58 UTC, jongnan commented on src/main/kotlin/mashup/backend/tdtd/room/repository/RoomRepository.kt
> +    @Query("update Room r set r.title =: newTitle where r.roomCode=:roomCode")
우리 프로젝트에서 report 도메인의 `ReportService`에서  `reportCommentByCommentId` 메소드 보면 신고 기능이잖아? 

여기 참고 하면 괜찮을듯?

로직은 신고시 디비 저장(예외처리) → 해당 신고물 카운팅 → 게시물 블라인드 처리(여기가 상태 변경 부분)

2021-07-28 21:42 UTC, YJeongKim commented on src/main/kotlin/mashup/backend/tdtd/host/dto/GetAlteredRoomNameRequest.kt
> +data class GetAlteredRoomNameRequest (
여기 Request 뒤에 아래와 같이 수정해주면 오류 해결됩니당
```kotlin
...Request @JsonCreator constructor(
   val altered_room_name: String
)
```
그리고 Room Entity의 title 프로퍼티를 변경하는거니까 변수명 `alteredRoomName` 대신 간단하게 `title`이나 `newTitle`이 어떨까요?!

2021-07-30 11:08 UTC, JaeHyeonKim19 requested changes
.DS_Store 삭제부탁해!

2021-07-30 11:08 UTC, JaeHyeonKim19 commented on src/main/kotlin/mashup/backend/tdtd/common/util/SeedDataInitializer.kt
> +@Profile("a")
테스트한다고 임시로 처리한 내용이 포함된거같아 수정부탁해!

2021-07-31 07:23 UTC, secureWKkim commented on src/main/kotlin/mashup/backend/tdtd/common/util/SeedDataInitializer.kt
> +@Profile("a")
와 맞아 말안해줬음 클났을뻔...
고마워 ㅠㅜ

2021-08-02 12:27 UTC, merged